# ruff: noqa
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import contextlib
import os
import json
from collections.abc import AsyncIterator
from pathlib import Path

import google.auth
from a2a.server.tasks import InMemoryTaskStore
from dotenv import load_dotenv
from fastapi import FastAPI, BackgroundTasks
from google.adk.cli.fast_api import get_fast_api_app
from google.adk.runners import Runner
from google.cloud import logging as google_cloud_logging

from app.app_utils import services
from app.app_utils.a2a import attach_a2a_routes
from app.app_utils.telemetry import setup_telemetry
from app.app_utils.typing import Feedback
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import uuid
from google.genai import types

# Load environmental configurations from the local .env file
load_dotenv()

# Setup OpenTelemetry configurations for monitoring request traces
setup_telemetry()

# =========================================================================
# Resilient Logging System Setup
# =========================================================================
# Standardizes logging outputs. If Google Cloud default authentication
# project credentials are not available locally (common during development),
# it gracefully falls back to the native Python logger to prevent startup crashes.
# =========================================================================
import logging

class FallbackLogger:
    def __init__(self, name):
        self.logger = logging.getLogger(name)
        logging.basicConfig(level=logging.INFO)
        
    def log_struct(self, info, severity="INFO"):
        self.logger.info(f"[{severity}] {json.dumps(info)}")

try:
    _, project_id = google.auth.default()
    logging_client = google_cloud_logging.Client()
    logger = logging_client.logger(__name__)
except Exception:
    logger = FallbackLogger(__name__)

# Allowed domains for CORS policies
allow_origins = (
    os.getenv("ALLOW_ORIGINS", "").split(",") if os.getenv("ALLOW_ORIGINS") else None
)

AGENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# =========================================================================
# FastAPI Lifespan Manager
# =========================================================================
@contextlib.asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """
    Manages startup and shutdown hooks for the server application.
    Initializes global services and telemetry exporters safely.
    """
    from app.agent import app as adk_app
    from app.agent import root_agent

    runner = Runner(
        app=adk_app,
        session_service=services.get_session_service(),
        artifact_service=services.get_artifact_service(),
        auto_create_session=True,
    )
    app.state.runner = runner
    app.state.agent_app_name = adk_app.name

    await attach_a2a_routes(
        app,
        agent=root_agent,
        runner=runner,
        task_store=InMemoryTaskStore(),
        rpc_path=f"/a2a/{adk_app.name}",
    )
    yield

# =========================================================================
# ADK FastAPI App Hook Configuration
# =========================================================================
# Configures the FastAPI wrapper generated by ADK to bind endpoints
# and expose underlying agent runtime schemas (including A2A protocols).
# =========================================================================
app: FastAPI = get_fast_api_app(
    agents_dir=AGENT_DIR,
    web=True,
    artifact_service_uri=services.ARTIFACT_SERVICE_URI,
    allow_origins=allow_origins,
    session_service_uri=services.SESSION_SERVICE_URI,
    otel_to_cloud=False,
    lifespan=lifespan,
)

# Remove default ADK redirect root route to serve static landing page directly
for route in list(app.routes):
    if route.path == "/":
        app.routes.remove(route)

# =========================================================================
# Endpoint: Trigger Documentation Generation (/generate)
# =========================================================================
# Handles incoming client requests, spawns the InMemoryRunner asynchronously,
# executes the multi-agent graph workflow, and returns the session token.
# =========================================================================
from pydantic import BaseModel

class GenerateRequest(BaseModel):
    repo_url: str
    guide_type: str
    description: str

@app.post("/generate")
async def generate_documentation_endpoint(req: GenerateRequest) -> dict[str, str]:
    """
    Receives GitHub repository URL, description, and guide type.
    Fires the ADK 2.0 Graph Workflow nodes asynchronously and returns
    the generated session UUID to enable subsequent file downloads.
    """
    runner = app.state.runner
    
    # Setup session inputs
    payload = {
        "repo_url": req.repo_url,
        "guide_type": req.guide_type,
        "description": req.description
    }
    
    # Create session using the pre-configured runner
    session = await runner.session_service.create_session(
        app_name=app.state.agent_app_name,
        user_id="web_user"
    )
    
    # Run the workflow graph nodes asynchronously and capture the output state
    session_id = None
    async for event in runner.run_async(
        user_id="web_user",
        session_id=session.id,
        new_message=types.Content(role="user", parts=[types.Part.from_text(text=json.dumps(payload))]),
    ):
        if event.actions and event.actions.state_delta:
            state_delta = event.actions.state_delta
            if "session_id" in state_delta:
                session_id = state_delta["session_id"]
                
    if not session_id:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail="The agent workflow failed to initialize the workspace.")
        
    return {
        "status": "success",
        "session_id": session_id
    }

# =========================================================================
# Static Assets Mount
# =========================================================================
os.makedirs("workspace_tmp", exist_ok=True)
app.mount("/workspace_tmp", StaticFiles(directory="workspace_tmp"), name="workspaces")
app.mount("/static", StaticFiles(directory="static"), name="static")

# =========================================================================
# Endpoint: Landing Page Server Root (/)
# =========================================================================
@app.get("/")
def read_root():
    """Serves the main frontend landing page HTML file."""
    return FileResponse("static/index.html")

# =========================================================================
# Endpoint: Session ZIP Download and Sandbox Cleanup (/download)
# =========================================================================
# Serves the compiled documentation.zip file.
# Spawns a FastAPI BackgroundTask that safely and forcefully deletes
# the temporary workspace directory immediately after dispatch completion.
# =========================================================================
@app.get("/download/{session_id}")
async def download_session_zip(session_id: str, background_tasks: BackgroundTasks):
    """
    Serves the output documentation.zip for the given session ID.
    Queues a background cleanup task to wipe the local sandbox files.
    """
    from app.agent import rmtree_force
    zip_path = Path("workspace_tmp") / session_id / "documentation.zip"
    
    if not zip_path.exists():
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="The file does not exist or has already been deleted.")
        
    def cleanup():
        import time
        time.sleep(2)  # Delay buffer to guarantee the FileResponse transfer has completed
        rmtree_force(Path("workspace_tmp") / session_id)
        
    # Queue the cleanup task to execute in the background after returning response
    background_tasks.add_task(cleanup)
    
    return FileResponse(
        path=zip_path,
        filename="documentation.zip",
        media_type="application/zip"
    )

# =========================================================================
# Endpoint: Feedback Collection (/feedback)
# =========================================================================
@app.post("/feedback")
def collect_feedback(feedback: Feedback) -> dict[str, str]:
    """Collects and logs frontend feedback data through structural log calls."""
    logger.log_struct(feedback.model_dump(), severity="INFO")
    return {"status": "success"}

# Main execution entry point
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host=os.getenv("HOST", "0.0.0.0"), port=int(os.getenv("PORT", 8000)))
